### ISSUE TITLE
Generating XSA or Platform returns an error for kr260

### ISSUE THREAD

**Issue by xlz-jbleclere** [Xilinx/kria-vitis-platforms#15]
Hi, I'm following instructions from the Xilinx doc, [this page](https://xilinx.github.io/kria-apps-docs/kr260/build/html/docs/build_vitis_platform.html#generating-an-vitis-extensible-platform) for the vitis flow and [this one](https://xilinx.github.io/kria-apps-docs/kr260/build/html/docs/build_vivado_design.html#generating-an-extensible-xsa) for vivado flow, but both are returning an error.

**On vitis, the command "make platform PFM=kr260_tsn_rs485pmod" returns this error:** 
ERROR: [Common 17-69] Command failed: This design contains one or more cells for which bitstream generation is not permitted:
kr260_tsn_rs485pmod_i/ta_dma_0/inst (<encrypted cellview>)
kr260_tsn_rs485pmod_i/my_tsn_ip/inst/tsn_endpoint_block_0/inst/TSN_TOP (<encrypted cellview>)

**On vivado, the command "make xsa" returns this error:** 
make: *** No rule to make target '/data/ip/xilinx/axi_uartlite_v2_0', needed by 'ip/axi_uartlite_v2_0'.  Stop.

Please advise?

**Comment by sweatharao** [comment]
Hi you need to request license for TSN IP as detailed on this page - https://xilinx.github.io/kria-apps-docs/kr260/build/html/docs/build_vivado_design.html

Info: To request TSN Subsystem IP evaluation license, send an email to [1gtsn_eval_request@amd.com](https://xilinx.github.io/kria-apps-docs/kr260/build/html/docs/1gtsn_eval_request@amd.com).

**Comment by chkohn** [comment]
@xlz-jbleclere can this issue be closed?

**Comment by xlz-jbleclere** [comment]
I've never received the TSN IP license, so I've never been able to complete the task. 
But I'm trying another path, so I guess it can be closed.
