### ISSUE TITLE
2022.1 kr260 platform bitstream generation not permitted.

### ISSUE THREAD

**Issue by JH989876525** [Xilinx/kria-vitis-platforms#19]
HI all,

I have request a evaluation license for TSN IP core and enable the license with vivado license manager.
![Untitled](https://user-images.githubusercontent.com/90902880/210045898-42e77a19-bc9e-4aeb-af1f-d0750c75d251.png)

But it still comes out following issue while I trying to build the platfrom.
```bash
make platform PFM=kr260_tsn_rs485pmod JOBS=4
```
![image](https://user-images.githubusercontent.com/90902880/210046007-54eda862-1c82-4d7c-a408-577546b369f8.png)

Any idea about this issue?

Thanks,
JH

**Comment by JH989876525** [comment]
Hi all,

After few days, I rebuild the project, and the bit stream could be generate properly.

It might needs to reboot or rebuild the project after adding a new license

Thanks,
JH

**Comment by Applepi** [comment]
big brain xilinx provides IP in example image that doesn't work for normal users. $30k IP... what a joke. Sent an email to sales, weeks later still nothing.
