### ISSUE TITLE
Error openning Vivado project using 2023.2 version

### ISSUE THREAD

**Issue by aalaba** [Xilinx/kria-vitis-platforms#26]
I am trying to open the Vivado project to see how it is configured and modify it, but I can't get it openned. I am following the steps mentioned [here](https://xilinx.github.io/kria-apps-docs/kd240/build/html/docs/build_vivado_design.html) but when I run _make xsa_ I get the following error: make [1]: vitis_hls: No such file or directory. (I am executing this command in the directory: _/kria-vitis-platforms-main/kd240/platforms/kd240_motor_ctrl_qei_ )

I have also tried running the _main.tcl_ from the TCL console but I get the error that the /xdc/pin_timing.xdc does not exist (screenshot attached). Any suggestions on how to open the Vivado project?

![Captura-source-command](https://github.com/user-attachments/assets/e706ff55-3871-4b64-abf9-b102b475922a)

The full TCL logs are: 
[logs-source-command.log](https://github.com/user-attachments/files/16977349/logs-source-command.log)

**Comment by sweatharao** [comment]
make [1]: vitis_hls: No such file or directory:  Likey you don't have Vitis HLS tools. You need Vitis hls tools to generate motor control IPs.

/xdc/pin_timing.xdc does not exist: You need to run the tcl script from this directory: /kria-vitis-platforms-main/kd240/platforms/kd240_motor_ctrl_qei. Command: vivado -source scripts/main.tcl. This will find the xdc file, but the IPs needed for motor control will not be generated and you will run into IP not found errors.

**Comment by aalaba** [comment]
Hello @sweatharao 

Thank you for answering. I am looking at the downloaded Xilinx tools and I do have Vitis HLS installed... could it be that the script is looking for the tool in another directory or so? I created a folder called tools2023.2 where I have all the tools downloaded, so I didn´t think there would be problems with the directories... 

Hope there ir an easy solution...

**Comment by aalaba** [comment]
Hello @sweatharao , 

I continue having the issue running the _make xsa_ command. As you said, if I run it from the TCL console the project opens but I have IP not found errors. 

Do you know how can I resolve the issue? I have all the Xilinx tools installed in /home/tools2023.2 directory, although if I try to run any of the apps from the terminal (with _vitis/vivado/vitis_hls..._ command) there is an error saying the command doesn't exist (independently of what the directory is), so I can only run the apps clicking the icon in the desktop. 

![vitis-command](https://github.com/user-attachments/assets/8ab01133-d9db-4828-b445-1fc105a74ec1)

Any ideas why this might be and if it is related to the main problem of this issue? 

Thank you!!
